name: PR Verify

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: PR Verify
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Test with the dotnet CLI
        run: dotnet test --configuration Release --no-build

      - name: verify format
        run: dotnet format -v detailed --verify-no-changes