name: Secretes workflow

on:
  workflow_dispatch:
  
# Define env variables which might be used during the workflow in multiple places. This is used for not secret things
env:
  API_CSPROJ_PATH: ./ExampleApi/ExampleApi.csproj
  

jobs:
  secrets:
    name: Secrets Demo
    runs-on: ubuntu-latest

    steps:
      - name: echo environment variables
        run: echo "$API_CSPROJ_PATH"