name: Secretes workflow

on:
  pull_request:
    branches: [ "master" ]
  
# Define env variables which might be used during the workflow in multiple places. This is used for not secret things
env:
  API_CSPROJ_PATH: ./ExampleApi/ExampleApi.csproj
  

jobs:
  secrets:
    name: Secrets Demo
    runs-on: ubuntu-latest

    steps:
      - name: echo environment variables
        run: echo "The value of my secret ${{secrets.SECRET_API_KEY}} for this project $API_CSPROJ_PATH" # The secret api key value will be masked in the job ***